# Generated by Django 4.2.27 on 2026-01-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(db_index=True, help_text='MAC address in format XX:XX:XX:XX:XX:XX', max_length=17, unique=True)),
                ('device_name', models.CharField(blank=True, help_text='Optional device name for identification', max_length=255)),
                ('m3u_url', models.URLField(help_text='URL to the M3U playlist file')),
                ('m3u_cache', models.TextField(blank=True, help_text='Cached M3U file content to avoid re-downloading')),
                ('m3u_cache_updated', models.DateTimeField(blank=True, help_text='Timestamp when M3U cache was last updated', null=True)),
                ('cache_expiry_hours', models.IntegerField(default=24, help_text='Number of hours before cache expires (default: 24)')),
                ('m3u_last_modified', models.DateTimeField(blank=True, help_text='Last modified timestamp from M3U source (for cache validation)', null=True)),
                ('m3u_etag', models.CharField(blank=True, help_text='ETag from M3U source (for cache validation)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this device is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the device was first registered')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Last time the device accessed the API')),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mac_address'], name='devices_mac_add_071ed3_idx'), models.Index(fields=['is_active', 'created_at'], name='devices_is_acti_8b397c_idx')],
            },
        ),
    ]
