# Generated by Django 4.2.27 on 2026-01-13 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Channel name', max_length=500)),
                ('url', models.URLField(help_text='Stream URL', max_length=2048)),
                ('logo', models.URLField(blank=True, help_text='Channel logo URL', max_length=2048, null=True)),
                ('group', models.CharField(blank=True, db_index=True, help_text="Group title (e.g., 'AR channels', 'FR channels')", max_length=255, null=True)),
                ('category', models.CharField(choices=[('LIVE_TV', 'Live TV'), ('MOVIES', 'Movies'), ('SERIES', 'Series'), ('OTHER', 'Other')], db_index=True, default='LIVE_TV', help_text='Channel category', max_length=50)),
                ('tvg_id', models.CharField(blank=True, help_text='TV Guide ID', max_length=255, null=True)),
                ('tvg_name', models.CharField(blank=True, help_text='TV Guide name', max_length=500, null=True)),
                ('tvg_logo', models.URLField(blank=True, help_text='TV Guide logo URL', max_length=2048, null=True)),
                ('order', models.IntegerField(db_index=True, default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the channel was first parsed')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the channel was last updated')),
                ('device', models.ForeignKey(help_text='Device that owns this channel', on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='devices.device')),
            ],
            options={
                'db_table': 'channels',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['device', 'category'], name='idx_device_category'), models.Index(fields=['device', 'group'], name='idx_device_group'), models.Index(fields=['device', 'category', 'group'], name='idx_device_cat_group'), models.Index(fields=['device', 'order'], name='idx_device_order'), models.Index(fields=['device', 'category', 'order'], name='idx_device_cat_order'), models.Index(fields=['device', 'name'], name='idx_device_name'), models.Index(fields=['group'], name='idx_group')],
                'unique_together': {('device', 'url')},
            },
        ),
    ]
