# Generated by Django 4.2.27 on 2026-01-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_channel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
