# Generated by Django 4.2.27 on 2026-01-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_delete_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='When the device was activated (for paid licenses)', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='activation_type',
            field=models.CharField(choices=[('FREE_TRIAL', 'Free Trial (7 days)'), ('YEARLY', 'Yearly (1 year)'), ('LIFETIME', 'Lifetime')], default='FREE_TRIAL', help_text='Type of activation/license', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the license expires (null for lifetime)', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_activity',
            field=models.DateTimeField(blank=True, help_text='Last time the app was used (heartbeat)', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this device is active (computed from activation status)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='m3u_url',
            field=models.URLField(blank=True, help_text='URL to the M3U playlist file (optional on first registration)', null=True),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['activation_type', 'expires_at'], name='devices_activat_4edc64_idx'),
        ),
    ]
